### ISSUE TITLE
wrs.nto and wrs.sto behavior related to Debug

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-zawrs#13]
The Zawrs specification states that the wrs.* instructions follow the rules of the WFI isntruction for resuming execution on a pending interrupt. 

How about the behavior of wrs.nto and wrs.sto related to Debug? The RISC-V Debug specification states the following related to WFI:

- When executing code due to an abstract command in debug mode 'the wfi instructions acts as a nop'.
- If halt is requested while wfi is executing, then the hart must leave the stalled state, completing this instruction’s execution, and then enter Debug Mode.
- If the instruction being stepped over is wfi and would normally stall the hart, then instead the
instruction is treated as nop.

Shall the wrs.nto and wrs.sto behave the same as the wfi instruction for above stated Debug specification points?

**Comment by ved-rivos** [comment]
The `wrs.nto` and `wrs.sto` should follow the `wfi` for interaction with `dcsr.step`, `icount`, and `haltreq`. 
@timsifive could we add a note in debug spec. Please tell me if I should send you a PR.

**Comment by timsifive** [comment]
@ved-rivos A PR seems like a great way to get this discussion started. We haven't officially decided whether we want to mention every future extension in the Debug Spec, but personally I think it does make sense. So make a PR, but maybe don't put too much effort into it just yet.

**Comment by ved-rivos** [comment]
Thanks. I have sent you https://github.com/riscv/riscv-debug-spec/pull/838/commits
