### ISSUE TITLE
Do LR and WRS need to be consecutive in the instruction stream?

### ISSUE THREAD

**Issue by stephen-ji** [riscv/riscv-zawrs#14]
I saw the following description in 'RISC-V Wait-on-Reservation-Set (Zawrs) extension' : 

> The instructions in the Zawrs extension are only useful in conjunction with the LR instructions, which are provided by the A extension

Do it means that LR and WRS need to be consecutive in the instruction stream? If there are other instructions between LR and WRS, will WRS take effect?

**Comment by ved-rivos** [comment]
There can be other instructions in the instruction stream but with similar restrictions noted in A extension apply i.e. only instructions from base "I" instruction set, excluding loads, stores, backward jumps, taken backward branches, JALR, fence, and system instructions.

**Comment by pdonahue-ventana** [comment]
> There can be other instructions in the instruction stream but with similar restrictions noted in A extension apply i.e. only instructions from base "I" instruction set, excluding loads, stores, backward jumps, taken backward branches, JALR, fence, and system instructions.

My understanding is that there are no constraints.  The limitation of only having base instructions is for constrained LR/SC loops (which is only for forward progress purposes).  Zawrs says that WRS instructions are explicitly not allowed in constrained LR/SC loops.  The very existence of a WRS instruction means that you're not in a constrained LR/SC loop which means that the constraints in the A extension don't apply.

**Comment by ved-rivos** [comment]
Yes, WRS is not allowed in constrained LR/SC loop. The constraints may want to be observed to allow for a reservation set to stay valid when the WRS is eventually invoked.

**Comment by pdonahue-ventana** [comment]
> The constraints may want to be observed to allow for a reservation set to stay valid when the WRS is eventually invoked.

Fair enough.

The answer probably depends on your goal.  If you want to arm the reservation and wake up when it's lost then you should follow the constraints.  On the other extreme, if you want to generate random tests for design verification then everything is well-defined so you can randomly include WRS without regard for any constraints (and you don't even need a preceding LR at all).

**Comment by ved-rivos** [comment]
Yes, WRS has a well defined behavior. The intended use case is to load a reservation set and wait on that reservation set.
