### ISSUE TITLE
Chapter integration into riscv-isa-manual repo.

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-zawrs#15]
Note that I'm beginning integration of this spec into the overal Unprivileged spec.  When a PR gets issued, I'll post it here.

**Comment by wmat** [comment]
I'd like to request a review of this spec as an integrated chapter within riscv-isal-manual unprivileged spec.  You can review the Unprivileged spec as a PDF [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7804432351/artifacts/1259712848).

**Comment by ved-rivos** [comment]
> I'd like to request a review of this spec as an integrated chapter within riscv-isal-manual unprivileged spec. You can review the Unprivileged spec as a PDF [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7804432351/artifacts/1259712848).

1. Chapter heading should be updated to "Zawrs" Standard extension for Wait-on-Reservation-Set instructions, version 1.01
2. Section 27.1 should be removed and the contributors merged into the the Preamble.
3. The section 27.2 heading should be removed.
4. Section 27.3 heading text change to "Wait-on-Reservation-Set Instructions"
5. A table should be included in Chapter 28 for Zawrs extension instructions.
@wmat

**Comment by wmat** [comment]
> > I'd like to request a review of this spec as an integrated chapter within riscv-isal-manual unprivileged spec. You can review the Unprivileged spec as a PDF [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7804432351/artifacts/1259712848).
> 
> 1. Chapter heading should be updated to "Zawrs" Standard extension for Wait-on-Reservation-Set instructions, version 1.01

Fixed.

> 2. Section 27.1 should be removed and the contributors merged into the the Preamble.

Fixed.

> 3. The section 27.2 heading should be removed.

Fixed.

> 4. Section 27.3 heading text change to "Wait-on-Reservation-Set Instructions"

Fixed.

> 5. A table should be included in Chapter 28 for Zawrs extension instructions.
>    @wmat

Would you like to add that table on the zawrs branch of riscv-isa-manual?

Fixed chapter 27 is [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7975614890/artifacts/1259818296).

**Comment by ved-rivos** [comment]
1. The Chapter title should be - "Zawrs" Standard Extension for Wait-on-Reservation-Set instructions, Version 1.01
2. Section 27.1 heading should be - "Wait-on-Reservation-Set instructions"
3. There are a couple of extra lines between note and section 27.1 that can be removed. That should also avoid the bulleted list under Operation from breaking across pages.
4. This sentence "The instructions in the Zawrs extension are only useful in conjunction with the LR instructions, which are provided by the A extension" should be updated "The instructions in the Zawrs extension are only useful in conjunction with the LR instruction, which is provided by the A extension" (change "LR instructions" to "LR instruction"; change "which are" to "which is")

> Would you like to add that table on the zawrs branch of riscv-isa-manual?

I will provide this.

@wmat

**Comment by ved-rivos** [comment]
> Would you like to add that table on the zawrs branch of riscv-isa-manual?

@wmat here is the table. I am unable to create a PR against the zawrs branch since the zawrs branch is not rebased to master and my PRs end up showing a lot of diff. Would you be able to take this table and add to your PR?

```
[%autowidth.stretch,float="center",align="center",cols="^2m,^2m,^2m,^2m,<2m,>3m, <4m, >4m, <4m, >4m, <4m, >4m, <4m, >4m, <6m"]
|===
15+^|*Zawrs Standard Extension*
 6+^|000000001101             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|WRS.NTO
 6+^|000000011101             2+^|00000 2+^|000    2+^|00000        2+^|1110011 <|WRS.STO
|===

```

**Comment by wmat** [comment]
Sure, can you let me know where to place the table in Chapter 28?

**Comment by ved-rivos** [comment]
It would go right after RV64Zfh table.

**Comment by wmat** [comment]
Fixed. Latest PDF [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7976901266/artifacts/1260133963).

**Comment by ved-rivos** [comment]
@wmat Couple of nits:
1. The V in "version 1.01" should be uppercase
2. The bullet c of the list starting on page 140 gets into page 141. Ideally the 3 bullets should be all on page 140 or we should add a page break to move the sentence starting "Hart execution..." to page 141. Maybe fixing the 3-4 empty lines that follow the note just preceeding section 27.1 may just fix it and make the 3 bullets just fit on page 140.
3. The sentence "The instructions in the Zawrs extension are only useful in conjunction with the LR instructions, which are provided by the A extension" should be changed to "The instructions in the Zawrs extension are only useful in conjunction with the LR instruction, which is provided by the A extension" - change "LR instructions" to "LR instruction" and change "which are" to "which is"

Rest looks good.

**Comment by wmat** [comment]
> @wmat Couple of nits:
> 
> 1. The V in "version 1.01" should be uppercase

Fix pushed.

> 2. The bullet c of the list starting on page 140 gets into page 141. Ideally the 3 bullets should be all on page 140 or we should add a page break to move the sentence starting "Hart execution..." to page 141. Maybe fixing the 3-4 empty lines that follow the note just preceeding section 27.1 may just fix it and make the 3 bullets just fit on page 140.

I added a pagebreak, however, we'll have to watch how this looks after integration is complete of the other chapters.

> 3. The sentence "The instructions in the Zawrs extension are only useful in conjunction with the LR instructions, which are provided by the A extension" should be changed to "The instructions in the Zawrs extension are only useful in conjunction with the LR instruction, which is provided by the A extension" - change "LR instructions" to "LR instruction" and change "which are" to "which is"

Fix pushed.

> 
> Rest looks good.

**Comment by ved-rivos** [comment]
> I added a pagebreak, however, we'll have to watch how this looks after integration is complete of the other chapters.

Thanks. Usually other chapters dont cause a change i.e. a given .adoc renders the same. Hope that holds.

This all looks good to me. Thanks!

**Comment by ved-rivos** [comment]
Marking this issue as resolved.

**Comment by wmat** [comment]
Awesome, thanks for the speedy review.  I'll ping Andrew for official merge advice.
