### ISSUE TITLE
Stall until reservation set invalid?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-zawrs#5]
Should the following:

> The `WRS.NTO` and `WRS.STO` instructions cause the hart to temporarily stall
> execution in a low-power state till the reservation set is valid or an 
> interrupt, even if disabled, is observed.

be corrected to:

> The `WRS.NTO` and `WRS.STO` instructions cause the hart to temporarily stall
> execution in a low-power state till the reservation set is **invalid** or an 
> interrupt, even if disabled, is observed.

**Comment by cmuellner** [comment]
Changes look good to me.
